dataset: {
    'dataset_names': [
        # 'm5',
        'vn1',
        # 'm4'
    ],
    'frequencies': [
        # 'daily', 
        'weekly'
    ],
    'ext': '.parquet'
}

model_names: [
    'ETS',
    'ARIMA', # no m5
    'LinearRegression', 
    'RandomForestRegressor', # no m5
    'XGBRegressor', 
    'LGBMRegressor', 
    'CatBoostRegressor', # no m4
    'MLP',
    'LSTM', # no m4, m5
    'TCN',
    'NBEATSx',
    'NHITS',
    'EnsembleMean2A',
    # 'EnsembleMean2T',
    'EnsembleMean3A',
    # 'EnsembleMean3T',
    'EnsembleMean4A',
    # 'EnsembleMean4T',
    'EnsembleMean5A',
    # 'EnsembleMean5T'
]
