
dataset: {
    'dataset_names': [
        'm5', 
        'm5', 
        # 'm5',
        'vn1', 
        'vn1'
    ],
    'frequencies': [
        'monthly', 
        'weekly',
        # 'daily', 
        'monthly', 
        'weekly'
    ],
    'ext': '.parquet'
}

models: {
    'model_names': [
        'LinearRegression', 
        'RandomForestRegressor', 
        'XGBRegressor',
        'LGBMRegressor', 
        'CatBoostRegressor',
        'MLP',
        'LSTM',
        'TCN',
        'NBEATSx',
        'NHITS',
        'EnsembleMeanMeanTOP3ACC',
        'EnsembleMeanTOP3TIME'
    ],
    'model_names_abbr': [
        'LR', 
        'RF', 
        'XGBoost', 
        'LGBM', 
        'CatBoost',
        'MLP',
        'LSTM',
        'TCN',
        'NBEATSx',
        'NHITS',
        'ENSacc',
        'ENStime'
    ]
}

evaluation: {
    metrics: [
        'bias', 
        'mae', 
        'mse', 
        'rmse', 
        'mase', 
        'msse', 
        'rmsse', 
        'mqloss', 
        'scaled_crps',
        # 'coverage_level50',
        # 'coverage_level60',
        # 'coverage_level70',
        # 'coverage_level80',
        # 'coverage_level90',
        # 'coverage_level95',
        # 'coverage_level99'
    ],
    time_metric: 'total_sample_time',
    evaluation_sample_type: 'overlap', # overlap / nooverlap
    analysis_type: 'absolute', # absolute / relative
}
