
dataset: {
    'dataset_name': 'm5',
    'frequency': 'daily',
    'ext': '.parquet'
}

fitting: {
    'horizon': 28,
    'test_window': 56, # test_window = 28 * 13 = 364
    'retrain_scenarios': [
        7, 
        14, 
        # 21,
        30, 
        60,
        # 90,
        # 120,
        # 150,
        # 180,
        # 364
    ]
}

ensembling: {
    model_names: [
        'LinearRegression', 
        # 'RandomForestRegressor', 
        # 'XGBRegressor', 
        'LGBMRegressor', 
        # 'CatBoostRegressor',
        'MLP',
        'NBEATSx'
    ],
    methods: ['mean'], # ['mean', 'median']
    name: 'LLMN'
}
