
seed: 1992
dataset_name: 'm5'
frequency: 'daily'
retrain_scenarios: [
    7, 
    14, 
    # 21,
    30, 
    60,
    # 90,
    # 120,
    # 150,
    # 180,
    # 364
]
model_names: [
    'LinearRegression', 
    'Lasso', 
    'Ridge', 
    'RandomForestRegressor', 
    'XGBRegressor', 
    'LGBMRegressor', 
    'CatBoostRegressor',
    'EnsembleMean',
    'EnsembleMedian'
]
metrics: ['bias', 'mae', 'mse', 'rmse', 'mase', 'msse', 'rmsse', 'mql', 'cov', 'scrps'] # 'ql', 'cal'
levels: [50, 60, 70, 80, 90, 95, 99]
evaluation_sample_type: 'overlap' # nooverlap
min_series_length: 730
samples: 100
ext: '.parquet'