
seed: 1992
dataset_name: 'm5'
frequency: 'daily'
horizon: 28
test_window: 56 # test_window = 28 * 13 = 364
retrain_scenarios: [7, 14, 30, 60] # retrain_scenarios = [7, 14, 21, 30, 60, 90, 120, 150, 180, 364]
model_names: ['LinearRegression', 'Lasso', 'LGBMRegressor']
# model_names = [
#     'LinearRegression', 'Lasso', 'Ridge', 
#     'RandomForestRegressor', 
#     'XGBRegressor', 'LGBMRegressor', 'CatBoostRegressor'
# ]
model_params: null
# model_params: {
#     'LinearRegression': {
#         'n_jobs': -1
#     },
#     'Lasso': {
#         'alpha': 0.5
#     },
#     'LGBMRegressor': {
#         'object': tweedie
#     },
# }
levels: [50, 60, 70, 80, 90, 95, 99]
static_features: ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id']
min_series_length: 730 # 365 * 2 = 730
samples: 100
store_in_sample_results: False
combine_results: False
ext: '.parquet'