dataset: {
    'dataset_names': [
        # 'm5', 
        # 'vn1',
        # 'm4',
        'hapag_region'
    ],
    'frequencies': [ 
        # 'daily',
        'weekly'
    ],
    'ext': '.parquet'
}

types: ['preds', 'eval', 'time']

model_names: [
    # 'ETS',
    # 'LinearRegression', 
    # 'XGBRegressor', 
    # 'LGBMRegressor', 
    'MLP',
    # 'NBEATSx'
]

# model_names_new: null
model_names_new: {
    # 'ETS': 'ETS',
    # 'LinearRegression': 'LR',
    # 'XGBRegressor': 'XGB',
    # 'LGBMRegressor': 'LGBM',
    'MLP': 'MLP_maxsteps1000_tuned_10years',
    # 'NBEATSx': 'NBEATSx'
}
