dataset: {
    'dataset_names': [
        'hapag_region'
    ],
    'frequencies': [ 
        'weekly'
    ],
    'ext': '.parquet'
}

types: ['preds'] # , 'eval', 'time'

model_names: [
    'Naive',
    'SeasonalNaive',
    'WindowAverage',
    'ETS',
    'ARIMA',
    'LinearRegression', 
    'XGBRegressor', 
    'LGBMRegressor', 
    'MLP',
    'NBEATSx'
]

model_names_new: null
# model_names_new: {
#     'Naive': 'Naive',
#     'SeasonalNaive': 'SeasonalNaive',
#     'WindowAverage': 'WindowAverage',
#     'ETS': 'ETS',
#     'ARIMA': 'ARIMA',
#     'LinearRegression': 'LR',
#     'XGBRegressor': 'XGBoost',
#     'LGBMRegressor': 'LGBM',
#     'MLP': 'MLP',
#     'NBEATSx': 'NBEATSx'
# }
