dataset: {
    'dataset_name': 'hapag_region',
    'frequency': 'weekly',
    'min_series_length': null,
    'max_series_length': null, 
    'samples': null, 
    'ext': '.parquet',
    'seed': 1992
}

fitting: {
    'retrain_scenarios': [
        # 1, 
        # 2, 
        # 3,
        # 4, 
        # 6,
        # 8,
        # 10,
        # 13,
        # 26,
        # 52
        104
    ],
    levels: [50, 60, 70, 80, 90, 95, 99],
    combine_only: False
}

model_names: [
    # 'ETS',
    # 'LinearRegression', 
    # 'XGBRegressor', 
    # 'LGBMRegressor', 
    'MLP',
    # 'NBEATSx'
]

evaluation: {
    metrics: ['bias', 'mae', 'mse', 'rmse', 'mase', 'msse', 'rmsse', 'mape', 'smape', 'mql', 'smql'],
    evaluation_frequency: 'yearly', 
    evaluation_sample_type: 'overlap',
    weighted_metrics: ['mape'],
    weights: 'auto'
}
