dataset: {
    'dataset_name': 'hapag_region',
    'frequency': 'weekly',
    'ext': '.parquet',
}

fitting: {
    'retrain_scenarios': [
        # 1, 
        # 2, 
        # 3,
        # 4, 
        # 6,
        # 8,
        # 10,
        # 13,
        # 26,
        # 52,
        104
    ],
    combine_only: False
}

model_names: [
    'Naive',
    'SeasonalNaive',
    'WindowAverage',
    'ETS',
    'LinearRegression', 
    'Lasso',
    'RandomForestRegressor',
    'XGBRegressor', 
    'LGBMRegressor', 
    'MLP',
    'NBEATSx',
    'NHITS'
]
