dataset: {
    'dataset_names': [
        # 'm5', 
        # 'vn1',
        # 'm4',
        'hapag_region'
    ],
    'frequencies': [ 
        # 'daily',
        'weekly'
    ],
    'ext': '.parquet'
}

model_names: [
    'Naive',
    'SeasonalNaive',
    'WindowAverage',
    'ETS',
    'LinearRegression', 
    'XGBRegressor', 
    'LGBMRegressor', 
    'MLP',
    'NBEATSx'
]
