
dataset: {
    dataset_name: 'vn1',
    frequency: 'monthly',
    min_series_length: 36,
    samples: null,
    ext: '.parquet',
    seed: 1992
}

fitting: {
    horizon: 6,
    test_window: 18,
    retrain_scenarios: [
        1, 
        2, 
        3,
        4, 
        5,
        6,
        9,
        12,
        15,
        18
    ],
    'intervals': {
        'h': 6,
        'n_windows': 2,
        'method': 'conformal_distribution'
    },
    levels: [50, 60, 70, 80, 90, 95, 99],
    store_in_sample_results: False
}

model_names: [
    'MLP',
    # 'LSTM',
    'TCN',
    'NBEATSx',
    'NHITS'
]
# model_params: null
model_params: {
    'MLP': {
        'h': 6,
        'input_size': 12,
        'max_steps': 500,
        'scaler_type': 'robust',
        'stat_exog_list': ['client', 'warehouse', 'product'],
        'futr_exog_list': ['year', 'quarter', 'month'],
        'random_seed': 1992 
    },
    'LSTM': {
        'h': 6,
        'input_size': 12,
        'max_steps': 500,
        'scaler_type': 'robust',
        'stat_exog_list': ['client', 'warehouse', 'product'],
        'futr_exog_list': ['year', 'quarter', 'month'],
        'random_seed': 1992 
    },
    'TCN': {
        'h': 6,
        'input_size': 12,
        'max_steps': 500,
        'stat_exog_list': ['client', 'warehouse', 'product'],
        'futr_exog_list': ['year', 'quarter', 'month'],
        'random_seed': 1992 
    },
    'NBEATSx': {
        'h': 6,
        'input_size': 12,
        'max_steps': 500,
        'scaler_type': 'robust',
        'n_harmonics': 2,
        'n_polynomials': 2,
        'stack_types': ['identity', 'trend', 'seasonality'],
        'stat_exog_list': ['client', 'warehouse', 'product'],
        'futr_exog_list': ['year', 'quarter', 'month'],
        'random_seed': 1992 
    },
    'NHITS': {
        'h': 6,
        'input_size': 12,
        'max_steps': 500,
        'scaler_type': 'robust',
        'stack_types': ['identity', 'identity', 'identity'],
        'stat_exog_list': ['client', 'warehouse', 'product'],
        'futr_exog_list': ['year', 'quarter', 'month'],
        'random_seed': 1992 
    }    
}
target_transforms: null
features: {
    'static': ['client', 'warehouse', 'product'],
    'lags': null,
    'lag_transforms': null,
    'date': ['year', 'quarter', 'month'],
    'xregs': null
}