
dataset: {
    'dataset_name': 'm5',
    'frequency': 'daily',
    'min_series_length': 730, 
    'max_series_length': null,
    'samples': null,
    'ext': '.parquet',
    'seed': 1992
}

fitting: {
    'horizon': 28,
    'test_window': 364,
    'retrain_scenarios': [
        7, 
        14, 
        21,
        30, 
        60,
        90,
        120,
        150,
        180,
        364
    ],
    'intervals': {
        'h': 28,
        'n_windows': 4,
        'method': 'conformal_distribution'
    },  
    'levels': [50, 60, 70, 80, 90, 95, 99],  
    'store_in_sample_results': False
}

model_names: [
    'LinearRegression', 
    'RandomForestRegressor', 
    'XGBRegressor', 
    'LGBMRegressor', 
    'CatBoostRegressor'
]
# model_params: null
model_params: {
    'LinearRegression': {'n_jobs': -1},
    'RandomForestRegressor': {
        'criterion': 'squared_error',
        'n_estimators': 300,
        'min_samples_leaf': 100,
        'max_features': 0.85,
        'max_depth': 6,
        'n_jobs': -1
    },
    'XGBRegressor': {
        'objective': 'reg:tweedie',
        'booster': 'gbtree',
        'n_estimators': 500,
        'learning_rate': 0.03,
        'max_leaves': 128,
        'subsample': 0.85,
        'colsample_bytree': 0.85,
        'eval_metric': 'rmse',
        'tweedie_variance_power': 1.1,
        'n_jobs': -1,
        'device': 'cuda'
    },
    'LGBMRegressor': {
        'objective': 'tweedie', # regression
        'boosting_type': 'gbdt',
        'n_estimators': 500,
        'learning_rate': 0.03,
        'num_leaves': 128,
        'min_child_samples': 100,
        'subsample': 0.85,
        'subsample_freq': 1,
        'colsample_bytree': 0.85,
        'metric': 'rmse',
        'tweedie_variance_power': 1.1,
        'boost_from_average': False,
        'n_jobs': -1,
        'device': 'gpu',
        'force_row_wise': True,
        'verbosity': -1
    },
    'CatBoostRegressor': {
        'loss_function': 'Tweedie:variance_power=1.1',
        'boosting_type': 'Plain',
        'n_estimators': 500,
        'learning_rate': 0.03,
        # 'max_leaves': 128, # not working with Tweedie
        'min_child_samples': 100,
        # 'subsample': 0.85,
        'eval_metric': 'RMSE',
        'thread_count': -1,
        'task_type': 'GPU',
        'logging_level': 'Silent',
        'allow_writing_files': False
    }
}
target_transforms: null
features: {
    'static': ['item_id', 'dept_id', 'cat_id', 'store_id', 'state_id'],
    'lags': [1, 7, 14, 21, 28, 35, 42, 49, 56],
    'lag_transforms': {
                1: [RollingMean(7), RollingMean(14), RollingMean(30), ExpandingMean()],
                7: [RollingMean(7), RollingMean(14), RollingMean(30)],
                14: [RollingMean(7), RollingMean(14), RollingMean(30)],
                30: [RollingMean(7), RollingMean(14), RollingMean(30)]
            },
    'date': ['year', 'quarter', 'month', 'week', 'dayofweek', 'day', is_weekend],
    'xregs': ['event']
}