
dataset: {
    'dataset_name': 'm5',
    'frequency': 'daily',
    'ext': '.parquet'
}

fitting: {
    horizon: 28,
    test_window: 364,
    retrain_scenarios: [
        7, 
        14, 
        21,
        30, 
        60,
        90,
        120,
        150,
        180,
        364
    ]
}

ensembling: {
    model_names: [
        ['XGBRegressor', 'LGBMRegressor', 'LinearRegression'],
        ['CatBoostRegressor', 'LinearRegression', 'XGBRegressor']
    ],
    methods: ['mean'], # ['mean', 'median']
    name: ['TOP3ACC', 'TOP3TIME']
}
