
dataset: {
    'dataset_names': ['m5', 'm5', 'vn1', 'vn1'],
    'frequencies': ['monthly', 'weekly', 'monthly', 'weekly'],
    'ext': '.parquet'
}

model_names: [
    'LinearRegression', 
    'RandomForestRegressor', 
    'XGBRegressor', 
    'LGBMRegressor', 
    'CatBoostRegressor'
]

evaluation: {
    evaluation_sample_type: 'overlap' # nooverlap
}


